<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '媒介平台',
    'measure_unit' => '30',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网络重卡媒体',
    'measure_unit' => '30',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '13',
    'cat_name' => '企业公众号',
    'measure_unit' => '50',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  3 => 
  array (
    'cat_id' => '10',
    'cat_name' => '网络重卡媒体',
    'measure_unit' => '30',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  4 => 
  array (
    'cat_id' => '14',
    'cat_name' => '意见领袖',
    'measure_unit' => '100',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  5 => 
  array (
    'cat_id' => '11',
    'cat_name' => '纸媒重卡媒体',
    'measure_unit' => '20',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  6 => 
  array (
    'cat_id' => '12',
    'cat_name' => '文案策划',
    'measure_unit' => '200',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  7 => 
  array (
    'cat_id' => '4',
    'cat_name' => '轻卡29+',
    'measure_unit' => '50',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '配件30+',
    'measure_unit' => '30',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '经销商300+',
    'measure_unit' => '300',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  10 => 
  array (
    'cat_id' => '3',
    'cat_name' => '重卡50+',
    'measure_unit' => '50',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
  ),
);
?>